<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Intrant extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Educazad_model');
    }

    /*
     * Listing of tb_am_users
     */
    function index()
    {
        $data['all_intrants'] = $this->Educazad_model->get_multiple('tb_im_carburants', array(), 'tb_im_carburants.intrant_id','DESC');

        $data['_view'] = 'intrants/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_am_user
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('qte_stock','Qte Stock','required');
        $this->form_validation->set_rules('libelle','Libelle','required');
        $this->form_validation->set_rules('prix_unitaire','Prix prix_unitaire','required');

        if($this->form_validation->run())
        {
            $current_datetime=date('Y-m-d H:i:s');
            $params = array(
                'libelle' => $this->input->post('libelle'),
                'qte_stock' => $this->input->post('qte_stock'),
                'prix_unitaire' => $this->input->post('prix_unitaire'),
                'date_ajout' => $current_datetime
            );
            $this->Educazad_model->insert_data('tb_im_carburants',$params);
            redirect('intrant/index');
        }
        else
        {
            $data['_view'] = 'intrants/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a tb_am_user
     */
    function edit($intrantID)
    {
        // check if the tb_am_user exists before trying to edit it
        //$data['candidat'] = $this->User_model->get_tb_am_user($id_asset);
        $data['intrant'] = $this->Educazad_model->get_one_row('tb_im_carburants', array('intrant_id'=>$intrantID));

        if(isset($data['intrant']))
        {
            $this->form_validation->set_rules('qte_stock','Qte Stock','required');
            $this->form_validation->set_rules('libelle','Libelle','required');
            $this->form_validation->set_rules('prix_unitaire','prix_unitaire','required');

            if($this->form_validation->run())
            {
                $current_datetime=date('Y-m-d H:i:s');
                $params = array(
                    'libelle' => $this->input->post('libelle'),
                    'qte_stock' => $this->input->post('qte_stock'),
                    'prix_unitaire' => $this->input->post('prix_unitaire'),
                    'date_modif' => $current_datetime
                );
                $this->Educazad_model->update_data('tb_im_carburants',$params, array('intrant_id'=>$intrantID));
                redirect('intrant/index');
            }
            else
            {
                $data['_view'] = ('intrants/edit');
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('Table non existant. ');
    }
}