<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class ShopVente extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Educazad_model');
    }

    /*
     * Listing of tb_am_users
     */
    function index()
    {
        $data['all_shops'] = $this->Educazad_model->get_multiple('tb_im_shops', array(), 'tb_im_shops.shop_id','DESC');

        $data['_view'] = 'shops/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_am_user
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('libelle','Libelle','required');
        $this->form_validation->set_rules('shop_adresse','Prix prix_unitaire','required');
        $this->form_validation->set_rules('shop_qte_stock','shop_qte_stock','required');

        if($this->form_validation->run())
        {
            $current_datetime=date('Y-m-d H:i:s');
            $qte_stock_init=$this->input->post('shop_qte_stock');
            $params = array(
                'shop_nom' => $this->input->post('libelle'),
                'shop_adresse' => $this->input->post('shop_adresse'),
                'date_ajout' => $current_datetime,
                'qte_totale_vendue'=>$qte_stock_init
            );
            $this->Educazad_model->insert_data('tb_im_shops',$params);
            redirect('ShopVente/index');
        }
        else
        {
            $data['_view'] = 'shops/add';
            $this->load->view('layouts/main',$data);
        }
    }
}